Add conditional ternary in BaseRepository
coders-app/coders-app-api-gateway pull request #10
Opened 2023-01-20 11:52 UTC by catatarelli

hice este ternario porque la config es opcional y si no se le pasa nada a createConfig, daba error el config.headers

2023-01-23 14:55 UTC, benjaminrae approved these changes

2023-01-23 17:42 UTC, MMLORENA commented
> hice este ternario porque la config es opcional y si no se le pasa nada a createConfig, daba error el config.headers

Justo iba a preguntar porqué era necesario pero ya me lo has aclarado. Gracias por el comentario

2023-01-23 17:42 UTC, MMLORENA approved these changes

2023-01-24 15:38 UTC, MMLORENA requested changes
¿Por qué has forzado un push?

2023-01-25 14:23 UTC, catatarelli commented
> ¿Por qué has forzado un push?

porque hablamos que era mejor quitar el metodo createConfig por los default headers de axios. Ahora esta arreglado

2023-01-25 16:12 UTC, MMLORENA approved these changes

2023-01-25 16:18 UTC, merged