Feature/cod 164 sctrict null checks configuration
coders-app/coders-app-api-gateway pull request #41
Opened 2023-04-09 11:33 UTC by Killuina

- He seteado la configuración `strictNullChecks` a true en tsconfig.json

- He añadido un guard en `loadEnvironment.ts` para que cuando no haya variables de entorno, salga un mensaje con feedback por consola de que faltan dichas variables y termine el proceso de node

- He añadido `req` y `next` a los tests de `errors` y `getPong` para no utilizar null y así adaptarlos a la nueva configuración.

2023-04-12 05:32 UTC, mariogl requested changes

2023-04-12 05:32 UTC, mariogl commented on src/loadEnvironments.ts
> +if (
Vamos a darle otro enfoque a esta comprobación. Antes de la línea 5 creamos un array con las variables obligatorias, y lo filtramos para ver si hay algunas no definidas (para cada variable, filter debería dejar pasar las que no existen en `process.env`).

Luego simplemente comprobamos si ese nuevo array tiene algún elemento, en ese caso tiramos el error y paramos el proceso.

2023-04-12 05:32 UTC, mariogl commented on src/server/middlewares/errors/errors.test.ts
> +const next: NextFunction = () => ({});
La función next no tiene que devolver nada.

2023-04-12 07:20 UTC, MMLORENA commented on .github/workflows/testing.yml
> +          SWAGGER_BASIC_AUTH_USERNAME: ${{ secrets.SWAGGER_BASIC_AUTH_USERNAME }}
¿Para qué test necesitamos añadir estás variables al workflow?

2023-04-13 08:49 UTC, Killuina commented on src/server/middlewares/errors/errors.test.ts
> +const next: NextFunction = () => ({});
Cierto, lo corregiré!

2023-04-13 08:52 UTC, Killuina commented on .github/workflows/testing.yml
> +          SWAGGER_BASIC_AUTH_USERNAME: ${{ secrets.SWAGGER_BASIC_AUTH_USERNAME }}
Como el guard nuevo comprueba si existen estas variables de entorno, cuando los tests pasan por este archivo si no pongo todas las que aparecen como condición entra en el if y se cierra el proceso, por eso las puse.

2023-04-13 09:01 UTC, Killuina commented on src/loadEnvironments.ts
> +if (
Perfecto, tomo nota.

2023-04-13 19:35 UTC, MMLORENA commented on .github/workflows/testing.yml
> +          SWAGGER_BASIC_AUTH_USERNAME: ${{ secrets.SWAGGER_BASIC_AUTH_USERNAME }}
Sigo sin entender bien en qué test se comprueba que estás variables existen. ¿Puedes explicarme más cómo funciona el guard?

2023-04-13 20:01 UTC, MMLORENA commented on .github/workflows/testing.yml
> +          SWAGGER_BASIC_AUTH_USERNAME: ${{ secrets.SWAGGER_BASIC_AUTH_USERNAME }}
Vale, ahora si lo veo. Gracias

2023-04-13 20:15 UTC, Killuina commented on .github/workflows/testing.yml
> +          SWAGGER_BASIC_AUTH_USERNAME: ${{ secrets.SWAGGER_BASIC_AUTH_USERNAME }}
Ahora soy yo la que no termina de entenderlo y me gustaría hacerlo! Yo entendía que era porque en el momento que se testee alguna función que dependa de una variable de entorno, node tendrá que pasar por el guard, y para que no se cierre el proceso el entorno de ejecucción de los tests necesitará todas las variables de entorno para que no se cumpla la condición. ¿Esto no sería correcto?

2023-04-13 20:17 UTC, mariogl commented on .github/workflows/testing.yml
> +          SWAGGER_BASIC_AUTH_USERNAME: ${{ secrets.SWAGGER_BASIC_AUTH_USERNAME }}
En nuestros tests importamos `loadEnvironment.ts`, así que testeemos lo que testeemos, se ejecutará lo que hay dentro.

2023-04-13 20:19 UTC, mariogl commented on .github/workflows/testing.yml
> +          SWAGGER_BASIC_AUTH_USERNAME: ${{ secrets.SWAGGER_BASIC_AUTH_USERNAME }}
(No los importamos directamente, pero en algún momento los tests hacen que JS pase por uno de esos import)

2023-04-13 20:19 UTC, Killuina commented on .github/workflows/testing.yml
> +          SWAGGER_BASIC_AUTH_USERNAME: ${{ secrets.SWAGGER_BASIC_AUTH_USERNAME }}
¡Toda la razón! Se me había pasado por completo, gracias.

2023-04-18 14:14 UTC, Killuina commented on src/loadEnvironments.ts
> +if (
Tengo una duda en cuanto a esto: no sería mejor crear el array en la línea 15, después de haber declarado las variables que apuntan a las variables de entorno de `process.env` para aprovecharlas?

2023-04-18 14:26 UTC, Killuina commented on src/loadEnvironments.ts
> +if (
Y a parte, se me ocurre otra solución que requiere menos líneas de código, a ver qué opinas: 

Una vez tengo el array, podría hacer un `forEach` que itere sobre el, y que por cada variable ejecute un condicional de que si no hay dicha variable, lanzo el error y paro el proceso.

2023-04-18 18:42 UTC, mariogl commented on src/loadEnvironments.ts
> +if (
Finalmente no hemos optado por esta vía, ¿no?

2023-04-18 18:45 UTC, Killuina commented on src/loadEnvironments.ts
> +if (
Efectivamente! Había hecho estos comentarios antes de preguntarlo en persona, así que como ya está resuelto resuelvo la conversación.

2023-04-19 16:31 UTC, Killuina commented
- He modificado la función `next` en el archivo `errors.test.ts` para que no devuelva nada
- He añadido color al mensaje de error del guard

2023-04-19 16:44 UTC, mariogl approved these changes

2023-04-19 19:56 UTC, Killuina commented
Cierro esta pull request porque he tenido que cambiar el nombre de la rama, porque estaba asociada al COD de la tarea madre.
Creo pull request con exactamente los mismos cambios en la nueva rama.

2023-04-19 19:56 UTC, closed without merging