Feature/base repository class
coders-app/coders-app-api-gateway pull request #9
Opened 2023-01-18 14:55 UTC by catatarelli

2023-01-18 15:13 UTC, catatarelli reviewed
@coders-app/devs puse la apiKey en la clase madre. Había entendido que la api-gateway se va a identificar al resto de backs con la misma api-key. Ahora estoy en la duda si va a tener una apiKey para cada micro servicio.

2023-01-18 17:05 UTC, benjaminrae commented
> 

Cada api tendra una sola api key asi que esta bien que se pone en la madre.

2023-01-18 17:07 UTC, benjaminrae commented on src/loadEnvironments.ts
> +  identityServerUrl,
Como es la unica URL lo veo bien, pero creo que mas adelante tendremos que usar un objeto con las urls de cada api.

2023-01-18 17:07 UTC, benjaminrae approved these changes

2023-01-19 04:15 UTC, mariogl requested changes
@catatarelli modifica el nombre de la rama para que siga la guía de contribución, please.

2023-01-19 09:49 UTC, merged

2023-01-19 11:34 UTC, mariogl commented on src/loadEnvironments.ts
> +  identityServerUrl,
@catatarelli @benjaminrae ¿se puede resolver esta conversación?

2023-01-19 11:35 UTC, benjaminrae commented on src/loadEnvironments.ts
> +  identityServerUrl,
> @catatarelli @benjaminrae ¿se puede resolver esta conversación?

Si, no creo que hace falta el cambio ahora mientras haya una sola URL